### ISSUE TITLE
[snake - homebrew] freezes at title screen

### ISSUE THREAD

**Issue by ITotalJustice** [ITotalJustice/TotalGB#38]
makes it to the title screen, however pressing start does nothing

![image](https://user-images.githubusercontent.com/47043333/118048157-c7d26f00-b373-11eb-954c-abd6927e62fc.png)

<https://gbhh.avivace.com/game/snake>

**Comment by Calindro** [comment]
Should be fixed by 26f8386. Looks like the same issues as #41

**Comment by ITotalJustice** [comment]
> Should be fixed by [26f8386](https://github.com/ITotalJustice/TotalGB/commit/26f838661e99cc4c7d32eadd76ccdebd4a93297a). Looks like the same issues as #41

Thanks for checking out the issues!

Sadly that commit didn't fix the issue 😞

**Comment by ITotalJustice** [comment]
turns out it relies on joypad interrupt (will commit a fix tomorrow, was in the middle of another commit)

![image](https://user-images.githubusercontent.com/47043333/122281653-68233280-cee2-11eb-8a8c-8389b8fd486d.png)
